apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkertest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: configcheckertest
        image: jagestah/configcheckertest
        volumeMounts:
        - name: secrets
          mountPath: '/etc/secrets'
          readOnly: true
        - name: log-volume
          mountPath: '/etc/logs'
        env:
         - name: PYTHON_DEVICE
           value: '10.4.84.10'
         - name: PYTHON_USERNAME
           value: 'ubnt'
      volumes:
      - name: secrets
        secret:
          secretName: ssh-user-pass
      - name: log-volume
        hostPath:
          path: /home/jj/logs/